source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project

target "InteractiveReports" do
    pod 'objective-zip', '0.8.3'
    pod 'TSMiniWebBrowser', '1.0.1'
end

